### ISSUE TITLE
[v 0.25] Produce to topic - select 'value schema' issue

### ISSUE THREAD

**Issue by haraldott** [tchiotludo/akhq#1846] opened 2024-06-26 14:58 UTC
When selecting a topic and then trying to produce to it, I can only see and select schemas that have the suffix _-value_ in the dropdown menu from **value schema**.
With the same setup, I was able to select from all available schemas when producing to a topic in the GUI in 0.24.
Yes, I have adapted the new group/roles layout from 0.24->0.25 - everything else works just fine.
I am also able to see all schemas in the **Schema Registry** overview, with 0.24 and with 0.25.

![Screenshot 2024-06-26 at 16 55 03](https://github.com/tchiotludo/akhq/assets/15214051/497fe59f-8df2-45b2-8e3b-66c6c6089444)

**Comment by AlexisSouquiere** [comment] 2024-06-27 05:58
Duplicate of #1795

**Closed by AlexisSouquiere** 2024-06-27 05:58 UTC

**Comment by haraldott** [comment] 2024-06-27 07:27
@AlexisSouquiere are you sure this is the same problem?
I've already seen issue 1795, but the problem described there is different.
