### ISSUE TITLE
Github SSO / OAuth2 support

### ISSUE THREAD

**Issue by cpflaume** [tchiotludo/akhq#1124] opened 2022-06-21 07:08 UTC
Hello, 

I was wondering if akhq has or plans to support oauth2 too. From my understanding only the better specified OIDC is supported.

I would like to connect akhq with Github SSO (Github OAuth App). There is currently no way to do this or am I missing something? Other than using an oauth security proxy in front of akhq?

Looking at the Micronaut documentation my guess is that supporting OAuth2 would require to implement some logic for every provider?

Micronaut on OAuth2 https://micronaut-projects.github.io/micronaut-security/3.0.1/guide/index.html#oauth2-authorization-code 
> Because a user information endpoint is not part of the OAuth 2.0 specification, it is up to you to provide an implementation to retrieve that information.

Thank you very much!

**Comment by tchiotludo** [comment] 2022-06-21 07:11
Hey, 

it's true, someone need to implement a Oauth2 mapper inside akhq. 
PR are welcome :tada: 

Closing since duplicate of #990

**Closed** 2022-08-30 06:21 UTC
