### ISSUE TITLE
Search / Pagination in topic data

### ISSUE THREAD

**Issue by ankon** [tchiotludo/akhq#473] opened 2020-10-22 08:51 UTC
It seems when searching in a topic there's a bunch of oddnesses:
1. The pagination control is very misleading, and seems to show the number of messages in total, not in the search result
2. The search term gets dropped when going to the second page
3. The search results seem to be un-ordered/out-of-order

**Comment by ankon** [comment] 2020-10-22 08:52
I might find time later today to look into these issues.

**Comment by polarising-java** [comment] 2020-11-19 15:10
@ankon  did you started looking at this?

**Comment by tchiotludo** [comment] 2020-11-19 15:12
@polarising-java I don't think :)

**Comment by ankon** [comment] 2020-11-19 16:07
I have not yet found the time for that, no. 

As a work-around you can always try to modify the URL directly to define where you want to start looking though.

**Comment by polarising-java** [comment] 2020-12-11 16:14
> It seems when searching in a topic there's a bunch of oddnesses:
> 
> 1. The pagination control is very misleading, and seems to show the number of messages in total, not in the search result
> 2. The search term gets dropped when going to the second page
> 3. The search results seem to be un-ordered/out-of-order

The topic data search is using an event stream to push the results into frontend. So the concept of pagination in the search makes no sense, we will have only 1 page with the results. Apply the sort ( NEWEST) in this case will be overkill, we have to consume all records, filter and then sort by date.

**Comment by tchiotludo** [comment] 2020-12-11 16:40
- on previous akhq version, the search stop after XXX elements and and let you click next to have the next result. 
- Agree that the NEWEST is not possible on search, maybe change to OLDEST when doing search will help people to understand this.
- The search result is sorted by kafka throu all partition, we have no control on that.

**Comment by xakassi** [comment] 2020-12-21 16:58
Hi, guys!
I'm looking at @polarising-java PR (Improve data search), that's great, thanks!

But I still can't understand why the pagination of search results is impossible (if I understand correctly "So the concept of pagination in the search makes no sense")?
I have a topic with 10000 records, search by a condition which should return almost all data, but search shows continuous loading, and then when I stop it after a few minutes it shows me only 50 records, and never shows more. It seems like not expected behavior. Could you, please, describe more detailed - is it technically difficult to add pagination to search results and load all search results and you do not want to do it in this PR, or I just do not understand something and all workes as expected?
Thanks!

**Comment by tchiotludo** [comment] 2020-12-22 08:04
@xakassi @polarising-java, pagination works on all akhq version with react : 
- there is a notion of [searchEnd and after](https://github.com/tchiotludo/akhq/blob/0.14.1/assets/modules/datas/search-sse.js)
- the server know the [size wanted](https://github.com/tchiotludo/akhq/blob/dev/src/main/java/org/akhq/repositories/RecordRepository.java#L618) and will stop when reaching the max size. 

This is not the case I think here and on actual PR, it seems that the option.size is simply not send @polarising-java ?

**Comment by polarising-java** [comment] 2020-12-23 10:48
I did some tests in DEV branch and the pagination is working but server only checks for max size after getting all messages from consumer.poll, so if akhq.clients-defaults.consumer.properties.max.poll.records = 50 and akhq.topic-data.size = 10, you will have a page with 50 records not 10.

**Comment by polarising-java** [comment] 2020-12-23 11:07
Testing on the PR, i see the same behavior, and i found another problem with the "KafkaWrapperRequestScope" class crashing when sending the "searchEnd", the search stays in loop. 
I changed KafkaWrapperRequestScope to @Singleton and set max.pool.records equals to topic-data.size and I have the expected results.

**Comment by xakassi** [comment] 2020-12-23 11:35
Hi, @polarising-java ! I'm testing the search using your branch `feat/impr ove_topic_data_search`. I will check again when you push new changes.

For now I have a few observations.
My dev case: I have a topic "test_string" with 12 records. Each record have a key "one_key" ("two_key", "three_key" and so on up to "twelve_key") and a value "one value" ("two value", ..., "twelve value").

I set akhq.clients-defaults.consumer.properties.max.poll.records=10 and akhq.topic-data.size = 10.

1) When I search by the condition `Key contains text "key"` (it should return all data), I see **continuous loading and no data**. When I click Stop, I see all data with pagination (I see 10 records on one page and 2 on the other).
![Search test case 1](https://user-images.githubusercontent.com/26784806/102992101-076afc80-4534-11eb-8352-c57978f2f2c5.png)

Is continuous load is ok?

2) When I search by the condition `Key not contains text "one"` (it should return all data except of the first record), I see **continuous loading and all data**. When I click Stop, I see all data on one page - 11 records.
![Search test case 2](https://user-images.githubusercontent.com/26784806/102992274-5dd83b00-4534-11eb-852d-43ce3088e1a4.png)

Here also continuous load is the question. And it seems a bit odd that sometimes I see data at once and sometimes only after "stop".

**Comment by polarising-java** [comment] 2020-12-23 11:39
Do you have error  in server with KafkaWrapperRequestScope ?

**Comment by xakassi** [comment] 2020-12-23 11:44
Yes, indeed "No bean of type [org.akhq.modules.KafkaWrapperRequestScope] exists for the given qualifier"

**Comment by polarising-java** [comment] 2020-12-23 11:46
Change in KafkaWrapperRequestScope "@RequestScope" to "@Singleton"

**Comment by xakassi** [comment] 2020-12-23 11:55
Works like a magic, thanks! :)
Now search works great and fast :)

I have only one observation now, but it's not really important for me. Sometimes search results are returned with pagination and sometimes they are returned on the one page. As I described in the previous message I have akhq.clients-defaults.consumer.properties.max.poll.records=10 and akhq.topic-data.size = 10, but when I search  for keys not containing "one" I have a result of 11 records on the one page. I'm not sure if it's bug or not.

**Comment by xakassi** [comment] 2020-12-23 11:58
And I also have an additional question not regarding this PR. For a topic content pagination I have only button for the next page, but it will be great to be able to return on the previous page, as it is done with topics list. Is it possible? Or did I just miss something?

**Comment by polarising-java** [comment] 2020-12-23 14:23
> Works like a magic, thanks! :)
> Now search works great and fast :)
> 
> I have only one observation now, but it's not really important for me. Sometimes search results are returned with pagination and sometimes they are returned on the one page. As I described in the previous message I have akhq.clients-defaults.consumer.properties.max.poll.records=10 and akhq.topic-data.size = 10, but when I search for keys not containing "one" I have a result of 11 records on the one page. I'm not sure if it's bug or not.

Yes, it can happen, the solution is to discard the rest of the records from the poll when reached the max page size. And in the next page we will fetch from the last matched record. It is possible to do this with multiple partitions @tchiotludo ?

**Comment by polarising-java** [comment] 2020-12-23 14:26
> And I also have an additional question not regarding this PR. For a topic content pagination I have only button for the next page, but it will be great to be able to return on the previous page, as it is done with topics list. Is it possible? Or did I just miss something?

Maybe if we save the last search positions we can apply it in previous page.

**Comment by tchiotludo** [comment] 2020-12-23 20:02
The previous page was removed from topic data also because it's some kind of complicated. 

You can use tricky things on client side (keep all the previous page, to allow back), but all of these don't make sense because we are not sure that Kafka will return the exact previous page. We are polling all the partition and there is no way to be sure that previous page will contain the same record and will not contain record show on the next page.

Also, If you share the current url, the client side don't contains previous page. Really hard to explain why the previous is here sometime or not. 

So it's an impossible things with actual Kafka api, so we will not implement the previous page anywhere for now.  

For the max per page, we do it best effort, i don't think it's a really hard issue to have some more records. 
We do polling by page. 10 in your examples, If we don't find on the first poll, we do a second one that can lead to more records than expected, but since the data is fetched, IMO, it's better to display it directly instead of contraint to limit.

**Comment by xakassi** [comment] 2020-12-24 06:07
Ok, thanks, understand :)
 I also think that it's better to display it directly instead of constraint to limit, just was curious about this behavior.

I have no other observations, now search seems absolutely fine and great for me, thank you, guys :)

**Comment by xakassi** [comment] 2020-12-24 06:10
I hope new version (new docker tag) will be released soon with this search fix and my Protobuf feature :)

**Closed** 2020-12-27 21:13 UTC
Labels: bug, ui
