### ISSUE TITLE
Failing to identifier leader when connecting to Azure EventHubs

### ISSUE THREAD

**Issue by justinmchase** [tchiotludo/akhq#1364] opened 2023-02-03 23:59 UTC
Azure EventHubs has a "kafka projection" mode. It looks a lot like kafka but has some subtle differences I think.

When attempting to connect to eventhubs akhq has an error:

> 2023-02-03 22:53:57,298 [1 31mERROR[0 39m [35mr-thread-5[0 39m [36mi.m.h.server.RouteExecutor[0 39m Unexpected error occurred: Error encoding object [org.akhq.utils.ResultPagedList@691ab908] to JSON: Leader not found (through reference chain: org.akhq.utils.ResultPagedList["results"]->org.akhq.utils.PagedList[0]->org.akhq.models.Topic["partitions"]->java.util.ArrayList[0]->org.akhq.models.Partition["leader"])

Here is my configuration:

#### application.yaml

```yaml
akhq:
  connections:
    kafka:
      properties:
        bootstrap.servers: "recovery-{{ .Values.global.envName }}.servicebus.windows.net:9093"
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="{{ .Values.global.AZURE_EVENT_HUBS_ENDPOINT }}";
```

#### https://github.com/tchiotludo/akhq/blob/dev/src/main/java/org/akhq/models/Partition.java#L40-L46

I believe this is the problem code, I belive that EventHubs is reporting that there are no replicas therefore the code to identify the leader is failing.

```java
    public Node.Partition getLeader() {
        return nodes
            .stream()
            .filter(Node.Partition::isLeader)
            .findFirst()
            .orElseThrow(() -> new NoSuchElementException("Leader not found"));
    }
```

Since there are no replicas, the `.findFirst()` finds nothing. I'm assuming the fix will be to either add the partition itself to the nodes list in the case where there are no replicas, or to return `this.id` in the `getLeader()` function instead of throwing an exception.

**Comment by tchiotludo** [comment] 2023-02-13 20:52
Event hub support can be cool, but I think it will break on other edge case, PR are welcome, closing due to duplicate of #657

**Closed by tchiotludo** 2023-02-13 20:52 UTC
Labels: enhancement, good first issue, backend

**Comment by justinmchase** [comment] 2023-02-18 19:01
Can you elaborate on what other edge cases you're worried about? It seems like the fix to make it work with event hubs would be pretty simple and I can test it against local single-instance and also GCP cluster. But if you were to elaborate on edge cases I could probably try to take that into consideration.

**Comment by tchiotludo** [comment] 2023-02-22 22:06
mostly I think on every specific feature like topic config / node config / compaction / etc ... that could not be implemented on event hub

**Comment by justinmchase** [comment] 2023-02-24 14:54
Ok as in, if this were fixed it may still experience more issues with EventHubs? You're not necessarily worried about this fix breaking non-EH systems?

**Comment by tchiotludo** [comment] 2023-02-24 14:57
maybe you will see other issues with EH, but I'm not worried at all for all non EH broker, exactly
