### ISSUE TITLE
Internal error when topic/data/read is missing

### ISSUE THREAD

**Issue by tarvip** [tchiotludo/akhq#514] opened 2020-11-17 10:26 UTC
I have to groups defined in my config:
```
groups:
  - name: group1
    roles:
      - topic/read
      - node/read
      - group/read
      - registry/read
  - name: group2
    roles:
      - topic/read
      - topic/data/read
      - node/read
      - group/read
      - registry/read
```

When logging in with privileges from group1 and clicking on Topic details button following error is shown:
```
Internal Server Error: Missing required configuration "bootstrap.servers" which has no default value.
org.apache.kafka.common.config.ConfigException: Missing required configuration "bootstrap.servers" which has no default value.
	at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:478)
	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:468)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:108)
...
```
If logging in with group2 privieleges there is no such issue. I think it is related to `topic/data/read` privilege. `bootstrap.servers` is set my config, otherwise I wouldn't see topic list at all.

**Comment by polarising-java** [comment] 2020-11-18 10:02
Duplicate of #498, already fixed.

**Closed** 2020-11-18 10:03 UTC
Labels: backend, bug, ui
